version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 590852515231.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI_1=590852515231.dkr.ecr.us-east-1.amazonaws.com/sri-training-phpapp
      - REPOSITORY_URI_2=590852515231.dkr.ecr.us-east-1.amazonaws.com/sri-training-mysql
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Php Docker image...
      - docker build -t $REPOSITORY_URI_1:latest .
      - docker tag $REPOSITORY_URI_1:latest $REPOSITORY_URI_1:$IMAGE_TAG
      - echo Building the Mysql Docker image...
      - docker build -t $REPOSITORY_URI_2:latest .
      - docker tag $REPOSITORY_URI_2:latest $REPOSITORY_URI_2:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_1:latest
      - docker push $REPOSITORY_URI_1:$IMAGE_TAG
      - docker push $REPOSITORY_URI_2:latest
      - docker push $REPOSITORY_URI_2:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo "[{'name':'sri-phpapp','imageUri':'$REPOSITORY_URI_1:$IMAGE_TAG'},{'name':'sri-mysql','imageUri':'$REPOSITORY_URI_2:$IMAGE_TAG'}]" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json